---
version: '2'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - ./data:/var/jenkins_home
      - .vagrant/machines/default/virtualbox/private_key:/var/jenkins_home/private_key
